### PR TITLE
[FIX] Link for downloading ffmpeg static build expired

### PR DESCRIPTION
**Pull request by zeroohub**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @zeroohub! I've created [OSPR-3168](https://openedx.atlassian.net/browse/OSPR-3168) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@zeroohub Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions.

**Comment by zeroohub** [comment]
> @zeroohub Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions.

I just signed the agreement and emailed to "legal@edx.org", please check.

**Comment by natabene** [comment]
@zeroohub Thank you for letting me know. It might take our team a couple of days to process it. Once you are all set, we will let you know.

**Comment by natabene** [comment]
@zeroohub Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward. @schenedx Can you give this a look?

**Comment by schenedx** [comment]
@fysheets

**Comment by natabene** [comment]
@fysheets Sorry, this is on hold until we solve legal piece.

**Comment by natabene** [comment]
@zeroohub Thank you for sorting out the legal piece. @fysheets , @schenedx We are all set to go, you can review at your earliest convenience.

**Review by fysheets — APPROVED** [review]
Thank you @schenedx for helping me to review here, and @zeroohub for your contribution. 👍

**Comment by openedx-webhooks** [comment]
@zeroohub 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/v_videocompile&entry.867055334=https://github.com/edx/v_videocompile/pull/3&entry.1484655318=https://github.com/zeroohub&entry.752974735=2019-03-04+09:05&entry.1917517419=2019-03-14+14:00&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
